.\" vim: tw=72 fdm=marker cms=.\\"\ %s
.
.\" FRONT MATTER {{{
.Dd Feb 16, 2016
.Os
.Dt SUMAXY 1
.
.Sh NAME
.Nm sumaxy
.Nd Query maintenance update metadata for repository URLs
.\" FRONT MATTER }}}
.
.\" SYNOPSIS {{{
.Sh SYNOPSIS
.Nm
.Fl h | \-help
.Nm
.Op Fl A | R
.Ar DIR
.Ar ARCH
.Op Ar PROD Ns ...
.\" SYNOPSIS }}}
.
.\" DESCRIPTION {{{
.Sh DESCRIPTION
.Nm
inspects metadata for a maintenance update, and
writes to standard output repository names and URLs
(or zypper commands to add or remove said repositories)
for specified architecture and product patterns.
.\" }}}
.
.\" OPTIONS {{{
.Sh OPTIONS
.
.Bl -tag -width "xx"
. It Fl h
Display usage instructions.
. It Fl \-help
Display full help.
. It Fl A , Fl \-addrepo
Output
. Nm zypper
. Fl n
. Cm ar
. Fl cgk
commands.
. It Fl R , Fl \-removerepo
Output
. Nm zypper
. Fl n
. Cm rr
commands.
.El
.\" }}}
.
.\" OPERANDS {{{
.Sh OPERANDS
.Bl -tag -width "xx"
.\" DIR
.It Ar DIR
Directory containing
. Pa project.xml
and
. Pa packages.xml
files for a maintenance update.
.\" ARCH
.It Ar ARCH
Architecture of requested repositories.
. Nm
will return only repositories
targeting
. Ar ARCH .
.\" PROD
.It Ar PROD
Product pattern.
If any product patterns are specified,
. Nm
will return only repositories for those products.
In the absence of product patterns,
. Nm
will return repositories for all products and versions
with published packages in the input files.
.El
.\" }}}
.
.\" INPUT FILES {{{
.Sh INPUT FILES
.Nm
consumes XML data in files listed below,
produced by the corresponding BuildService API endpoints.
An easy way to create these files is by using
.Xr smrt-fetch 1 .
.
.Bl -tag -width "xx"
.It Ar DIR Ns Pa /packages.xml
. Nm osc Cm api Li \&"/search/published/binary/id?match=project=' Ns Va $mprj Ns Li '&limit=0"
.It Ar DIR Ns Pa /project.xml
. Nm osc Cm api Li \&"/source/ Ns Va $mprj Ns Li /_meta"
.El
.\" }}}
.
.\" STDOUT {{{
.Sh STDOUT
By default,
each line of output contains a repository name / URL pair
separated by a single space.
.
If either
.Fl A
or
.Fl R
is given,
each line of output contains a
.Nm zypper Cm addrepo
or
.Nm zypper Cm removerepo
command line.
.\" }}}
.
.\" EXTENDED DESCRIPTION {{{
.Sh EXTENDED DESCRIPTION
.\" Product patterns {{{
.Sy Product patterns
are
.Em EXTENDED_GLOB
patterns (see
.Xr zshexpn 1 Ns ),
and are used to match strings of this format:
.Pp
.
.Bd -ragged -offset "xx"
. Ar P Ns Li : Ns Ar V
.Pp
.Bl -tag -compact -width "xx"
.It Ar P
is a product name
.It Ar V
is a version string
.El
.Ed
.Pp
.\" }}}
.
.\" Product names {{{
.Sy Product names
are the variety found in
.Pa /etc/products.d/*.prod
files
(XPath:
.Pa /product/name/text() Ns ).
.Dq Li SUSE_SLES ,
.Dq Li SLES ,
and
.Dq Li sles
are
equivalent; same with
.Dq Li SUSE_SLED ,
.Dq Li SLED ,
and
.Dq Li sled .
.Pp
.\" }}}
.
.\" Architecture names {{{
.Sy Architecture names
are the variety found in
.Pa /etc/products.d/*.prod
files
(XPath:
.Pa /product/arch/text() Ns ).
.Pp
.\" }}}
.
.\" Version strings {{{
.Sy Version strings
use the
.Ar MAJOR Ns Li . Ns Ar MINOR
format,
.Ar MINOR
may have the form
.Li sp Ns Ar N
where
.Ar N
is a number.
.Dq Li 12.1 ,
.Dq Li 12.sp1 ,
.Dq Li 12.SP1
are equivalent.
.Pp
.\" }}}
.
.\" Repository names {{{
.Sy Repository names
output by
.Nm
conform to the following format:
.
.Bd -ragged -offset "xx"
. Ar P Ns Li : Ns Ar V Ns Li ::p= Ns Ar I
.Pp
.Bl -tag -compact -width "xx"
.It Ar P
is a product name
.It Ar V
is a version string
.It Ar I
is an issue (patch) number
.El
.Ed
.Pp
.\" }}}
.\" }}}
.
.\" EXAMPLES {{{
.Sh EXAMPLES
Show
.Li x86_64
repositories for SLE-SERVER and SLE-SDK 12-SP1:
.Bd -literal -offset "xx"
$ sumaxy . x86_64 sles:12.1 sle-sdk:12.1
.Ed
.Pp
Show
.Li s390x
repositories for SLE-SERVER 12-SP1 and SUSE Enterprise Storage:
.Bd -literal -offset "xx"
$ sumaxy . s390x sles:12.1 ses
.Ed
.Pp
Show
.Li ppc64le
repositories for SLE-SERVER 12-SP1, SLE-DESKTOP 12,
and SLE-SDK 12-SP1:
.Bd -literal -offset "xx"
$ sumaxy . ppc64le sles:12.1 sle-sdk:12.1 sled:12
.Ed
.\" }}}
.
.\" SEE ALSO {{{
.Sh SEE ALSO
.Xr refdb 1 ,
.Xr repose 1 ,
.Xr smrt 1 ,
.Xr zshexpn 1 .
.\" }}}
.
.\" AUTHORS {{{
.Sh AUTHORS
.An Roman Neuhauser Aq Mt rneuhauser+sumaxy@sigpipe.cz
.\" AUTHORS }}}
.
.\" BUGS {{{
.Sh BUGS
No doubt plentiful.
Please report them at
.Lk https://github.com/openSUSE/sumaxy/issues
.\" BUGS }}}
