language: c

os: linux
dist: xenial

before_install:
        - sudo apt-get -qq update
        - sudo apt-get install -y xmlstarlet
        - sudo apt-get install -y zsh
        - sudo apt-get install -y realpath
        - sudo apt-get install -y python-docutils
        - sudo pip install cram
        - git clone https://github.com/roman-neuhauser/haveopt.git
        - pushd haveopt && PREFIX=/usr make && sudo make install && popd
        - sudo ln -s /usr/bin/xmlstarlet /usr/bin/xml


script: ./configure && make && make check
